Compare forecast in situ data for single city part two
ECMWFCode4Earth/vAirify pull request #198
Opened 2024-07-10 14:26 UTC by Ben-EJ

![image](https://github.com/user-attachments/assets/4884f5a7-85a1-44a0-acc1-cc67ebca7f14)

2024-07-10 16:32 UTC, lincent commented on air-quality-ui/src/components/single-city/single-city/SingleCity.tsx
I think these SingleCity component ifles can live in the parent directory. Not keen on having single-city/single-city/SingleCity.xyz. As this is the main page component I think it's absolutely fine to have it on the parents and have the chart components as subdirectories..

2024-07-15 10:08 UTC, lincent requested changes
looks good, just a few comments.

Fancy converting the new code to arrow functions?

2024-07-16 12:45 UTC, lincent approved these changes

2024-07-16 12:48 UTC, rstrange-scottlogic approved these changes

2024-07-16 12:48 UTC, merged